name: bliss
description: An easy to learn server side framework for Dart.
version: 0.0.1
author: Steven Upton <steven.upton@indecks.co>
homepage: https://github.com/stwupton/bliss

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'