name: bliss
description: An easy to learn server side framework for Dart.
version: 0.3.0
author: Steven Upton <steven.upton@indecks.co>
homepage: https://github.com/stwupton/bliss

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  mime: '>=0.9.3 <0.10.0'
  path: ^1.0.0

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
